language: go

go: 1.9.x
go_import_path: kubevirt.io/kubernetes-device-plugins

script: make build test docker-build

deploy:
  - provider: script
    skip_cleanup: true
    script: docker login -u="phoracek+device_plugin_bot" -p="${DOCKER_PASS}" quay.io && make docker-push
    on:
      all_branches: true
